apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators



resources:
- CatalogSource.yaml

configurations:
- kustomizeconfig/CatalogSource.yaml

images:
- name: catalog
  newName: catalog
  newTag: latest
